DOMAIN = "custom_device_notifier"

CONF_SERVICE_NAME = "service_name"
CONF_SERVICE_NAME_RAW = "service_name_raw"
CONF_TARGETS = "targets"
CONF_PRIORITY = "priority"
CONF_FALLBACK = "fallback"
CONF_MATCH_MODE = "match_mode"

KEY_SERVICE = "service"
KEY_CONDITIONS = "conditions"
KEY_MATCH = "match"

STEP_USER = "user"
STEP_ADD_TARGET = "add_target"
STEP_ADD_COND_ENTITY = "add_condition_entity"
STEP_ADD_COND_VALUE = "add_condition_value"
STEP_COND_MORE = "condition_more"
STEP_REMOVE_COND = "remove_condition"
STEP_MATCH_MODE = "match_mode"
STEP_TARGET_MORE = "target_more"
STEP_ORDER_TARGETS = "order_targets"
STEP_CHOOSE_FALLBACK = "choose_fallback"
