[tool.mypy]
python_version = "3.11"

# ── suppress unavoidable noise ───────────────────────────────────────────────
ignore_missing_imports = true                    # libs without stubs → Any
namespace_packages = true
explicit_package_bases = true

# ── stricter checks you want ────────────────────────────────────────────────
check_untyped_defs = true
no_implicit_optional = true
warn_redundant_casts = true
warn_unused_ignores = true
warn_return_any = true
