[tool.mypy]
python_version = "3.11"

# third-party libraries without stubs
ignore_missing_imports = true

# treat namespace package correctly
namespace_packages = true

# your preferred strictness
check_untyped_defs = true
no_implicit_optional = true
warn_redundant_casts = true
warn_unused_ignores = true
warn_return_any = true