[tool.mypy]
python_version = "3.11"

# ── Silence 3rd-party stub issues ────────────────────────────────────────────
ignore_missing_imports = true        # treat unknown libs as Any
disable_error_code = ["import-untyped"]

# ── Namespace / package handling ─────────────────────────────────────────────
explicit_package_bases = true        # prevent duplicate-module error
namespace_packages = true            # allow namespace packages

# ── Other checks you already wanted ─────────────────────────────────────────
check_untyped_defs = true
no_implicit_optional = true
warn_redundant_casts = true
warn_unused_ignores = true
warn_return_any = true

# Which code to scan
files = "custom_components/custom_device_notifier"
