[tool.mypy]
python_version = "3.11"
ignore_missing_imports = true      # ignore third-party libs without stubs
explicit_package_bases = true      # avoid duplicate-module error
check_untyped_defs = true
no_implicit_optional = true
warn_redundant_casts = true
warn_unused_ignores = true
warn_return_any = true
files = "custom_components/custom_device_notifier"
