[tool.mypy]
python_version = "3.11"

# ── third-party libs without stubs ───────────────────────────────────────────
ignore_missing_imports = true
disable_error_code = ["import-untyped"]    # silence “module installed, no stubs”

# ── namespace / duplicate-module handling ───────────────────────────────────
explicit_package_bases = true
namespace_packages = true

# ── other strictness you wanted ─────────────────────────────────────────────
check_untyped_defs = true
no_implicit_optional = true
warn_redundant_casts = true
warn_unused_ignores = true
warn_return_any = true

# Let mypy discover files itself (no ‘files =’ to avoid double-scan)
