[tool.mypy]
python_version = "3.11"

# 3rd-party libs without stubs
ignore_missing_imports = true
disable_error_code = ["import-untyped", "duplicate-module"]

# namespace handling
namespace_packages = true
explicit_package_bases = true

# stricter checks
check_untyped_defs = true
no_implicit_optional = true
warn_redundant_casts = true
warn_unused_ignores = true
warn_return_any = true
