[tool.mypy]
python_version = "3.11"

# third-party libs (voluptuous, homeassistant) ship no stubs
ignore_missing_imports = true

# regular package semantics now that the marker file exists
namespace_packages = false
explicit_package_bases = true

# keep your useful strictness
check_untyped_defs = true
no_implicit_optional = true
warn_redundant_casts = true
warn_unused_ignores = true
warn_return_any = true
