[tool.mypy]
python_version = "3.13"

# third-party libs have no stubs
ignore_missing_imports = true

# use the same package-base logic Frigate uses
namespace_packages = true
explicit_package_bases = true

# keep real checks
check_untyped_defs      = true
no_implicit_optional    = true
warn_return_any         = true
warn_unused_ignores     = true
# Add this line so mypy knows what to check without CLI args
files = ["custom_components/custom_device_notifier"]

# pyproject.toml
[tool.ruff]
line-length = 88

[tool.ruff.format]
skip-magic-trailing-comma = false       # Black defaults
docstring-code-format      = true

[tool.pytest.ini_options]
asyncio_mode = "auto"
