[tool.mypy]
python_version = "3.11"

# ── silence unavoidable Home-Assistant / voluptuous stub warnings ───────────
ignore_missing_imports = true
disable_error_code = ["import-untyped", "duplicate-module"]

# ── keep strictness for *your* code ─────────────────────────────────────────
check_untyped_defs = true
no_implicit_optional = true
warn_redundant_casts = true
warn_unused_ignores = true
warn_return_any = true
