[tool.mypy]
python_version = "3.11"
ignore_missing_imports = true

disable_error_code = ["duplicate-module"]   # ← add this

check_untyped_defs = true
no_implicit_optional = true
warn_return_any = true
warn_unused_ignores = true
