[tool.mypy]
python_version = "3.13"

# third-party libs have no stubs
ignore_missing_imports = True

# use the same package-base logic Frigate uses
namespace_packages = True
explicit_package_bases = True
mypy_path = custom_components

# keep real checks
check_untyped_defs      = True
no_implicit_optional    = True
warn_return_any         = True
warn_unused_ignores     = True
