[tool.mypy]
python_version = "3.11"
ignore_missing_imports = true

# namespace_packages = false   ←  can omit; default is fine
# explicit_package_bases = true ←  **delete this line**

check_untyped_defs = true
no_implicit_optional = true
warn_return_any = true
warn_unused_ignores = true
