name: CI-dev

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: "bash -euo pipefail {0}"

    steps:
      # ▸ 1 Check out code
      - uses: actions/checkout@v4

      # ▸ 2 Python with pip-cache handled by setup-python
      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"
          cache: "pip"
          cache-dependency-path: |
            .tools/requirements-ci.txt
            .tools/constraints.txt
            pyproject.toml            # only these files bust the cache

      # ▸ 3 Install deps
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r .tools/requirements-ci.txt -c .tools/constraints.txt

      # ▸ 4 (OPTIONAL) Show pip-cache size, but don’t fail if missing
      - name: Show pip-cache size
        run: |
          [[ -d ~/.cache/pip ]] && du -sh ~/.cache/pip || echo "No pip cache yet"

      # ▸ 5 Cache mypy’s incremental files
      - uses: actions/cache@v4
        with:
          path: .mypy_cache
          key: >-
            mypy-${{ runner.os }}-${{ hashFiles('.tools/requirements-ci.txt',
                                               '.tools/constraints.txt',
                                               'pyproject.toml') }}-v1
          restore-keys: mypy-${{ runner.os }}-

      # ▸ 6 Lint + type-check
      - name: Lint / type-check
        run: |
          ruff check .
          black --check .
          flake8 . --max-line-length 88
          mypy custom_components/custom_device_notifier --config-file custom_components/custom_device_notifier/pyproject.toml

      # ▸ 7 Unit tests
      - name: Run tests
        run: pytest -q
