name: CI-dev

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"
          cache: "pip"

      - uses: actions/cache@v4
        with:
          key: "pip-${{ hashFiles('.tools/requirements-ci.txt') }}-py3.13"
          path: ~/.cache/pip

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r .tools/requirements-ci.txt
          # latest Home-Assistant dev wheel
          pip install --no-cache-dir --pre \
            "https://github.com/home-assistant/core/releases/download/dev/homeassistant-0.dev0-py3-none-any.whl"

      - name: Lint / type-check
        run: |
          ruff check .
          black --check .
          flake8 .
          mypy custom_components/custom_device_notifier

      - name: Run tests
        run: pytest -q
