name: CI
permissions:
  contents: write         # needed only when Black pushes fixes

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

###############################################################################
# 1️⃣  Lint / Static analysis (fast)                                           #
###############################################################################
jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install lint dependencies
        run: |
          python -m pip install --upgrade "pip<23.2"
          pip install \
            ruff \
            black \
            flake8 \
            mypy \
            "homeassistant-stubs==2023.7.3"

      # Ruff (style / simple rules)
      - name: Ruff style check
        run: ruff check .

      # Black (auto-format)
      - name: Black format
        run: black . --line-length 88

      # Flake8 (extra linting)
      - name: Flake8 lint
        run: flake8 --max-line-length 88 .

      - name: Mypy type check
        run: |
          mypy --namespace-packages --explicit-package-bases \
               -p custom_components.custom_device_notifier

      # Commit Black fixes back to `main`
      - name: Commit Black fixes
        if: ${{ github.event_name == 'push' }}
        uses: EndBug/add-and-commit@v9
        with:
          message: "chore: format code with Black [skip ci]"
          add: "."
          pull: "--rebase --autostash"
          push: true

###############################################################################
# 2️⃣  Tests (runs only if lint passes)                                        #
###############################################################################
  test:
    runs-on: ubuntu-latest
    needs: lint

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install test / HA dependencies
        run: |
          python -m pip install --upgrade "pip<23.2"
          pip install \
            pytest \
            pytest-mock \
            gitpython \
            "homeassistant==2023.7.3" \
            "homeassistant-stubs==2023.7.3"

      - name: Run pytest
        run: pytest tests/ --maxfail=1 --disable-warnings -q
