name: CI
permissions:
  contents: write       # needed when Black pushes auto-fixes

on:
  push:        { branches: [main] }
  pull_request: { branches: [main] }

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

###############################################################################
# 1️⃣  HassFest – Home-Assistant manifest/translation lint (3 s)               #
###############################################################################
jobs:
  hassfest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }

      - name: HassFest
        uses: home-assistant/actions/hassfest@master

###############################################################################
# 2️⃣  Lint / static analysis (fast)                                           #
###############################################################################
  lint:
    runs-on: ubuntu-latest
    needs: hassfest                       # run after HassFest

    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"                    # built-in pip cache

      - name: Install lint deps
        run: |
          python -m pip install --upgrade "pip<23.2"
          pip install \
            ruff \
            black \
            flake8 \
            mypy \
            "homeassistant-stubs==2023.7.3"

      - name: Ruff
        run: ruff check .

      - name: Black
        run: black . --line-length 88

      - name: Flake8
        run: flake8 --max-line-length 88 .

      - name: Mypy
        run: |
          mypy --explicit-package-bases \
              -p custom_components.custom_device_notifier

      - name: Commit Black fixes
        if: github.event_name == 'push'
        uses: EndBug/add-and-commit@v9
        with:
          message: "chore: format code with Black [skip ci]"
          add: "."
          pull: "--rebase --autostash"
          push: true

###############################################################################
# 3️⃣  Tests – matrix over HA versions                                         #
###############################################################################
  test:
    runs-on: ubuntu-latest
    needs: lint

    strategy:
      matrix:
        ha: ["2023.7.3", "2024.2.0"]      # test against two core versions

    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }

      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: "pip"

      # Cache heavy wheels (Home Assistant, aiohttp, etc.)
      - name: Cache HA wheels
        uses: actions/cache@v4
        with:
          key: ha-wheels-${{ runner.os }}-${{ matrix.ha }}
          restore-keys: ha-wheels-${{ runner.os }}-
          path: ~/.cache/pip

      - name: Install test deps
        run: |
          python -m pip install --upgrade "pip<23.2"
          pip install \
            pytest pytest-mock gitpython \
            "homeassistant==${{ matrix.ha }}" \
            "homeassistant-stubs==${{ matrix.ha }}"

      - name: Run pytest
        run: pytest tests/ --maxfail=1 --disable-warnings -q
