name: CI-dev

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Python setup **with built‑in pip cache**
      - name: Set up Python + pip cache
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
          cache: "pip"
          # Hash these files to build the cache‑key.  Add more paths if you pin deps elsewhere.
          cache-dependency-path: |
            .tools/requirements-ci.txt
            **/pyproject.toml

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r .tools/requirements-ci.txt -c .tools/constraints.txt
      - name: Cache mypy
        uses: actions/cache@v4
        with:
          path: .mypy_cache
          key: mypy-${{ github.ref }}-${{ hashFiles('**/*.py') }}
          restore-keys: |
            mypy-${{ github.ref }}-
            mypy-

      - name: Lint / type‑check
        run: |
          ruff check .
          black --check .
          flake8 . --max-line-length 88
          # Explicitly point mypy at the root‑level config to avoid the lookup confusion
          mypy -p custom_device_notifier

      - name: Run tests
        run: pytest -q
