# .github/workflows/lint.yml
name: Lint & Auto-Fix with Ruff

# ONLY run on PRs (opened, synchronize, reopened)
on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

# If someone pushes again to the same PR, cancel the older lint run
concurrency:
  group: lint-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      # 1) Checkout with PAT support
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0           # we need full history to push back
          persist-credentials: true

      # 2) Python + Ruff
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install Ruff
        run: |
          python -m pip install --upgrade pip
          pip install ruff

      # 3) Run auto-fix
      - name: Auto-fix with Ruff
        run: ruff check . --fix --unsafe-fixes

      # 4) Commit & push only on PRs
      - name: Commit & push fixes
        if: github.event_name == 'pull_request'
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          git config user.name  "ci-bot"
          git config user.email "ci-bot@users.noreply.github.com"
          git add .
          if ! git diff --cached --quiet; then
            git commit -m "chore: auto-fix with Ruff"
            git push "https://${GH_PAT}@github.com/${{ github.repository }}" HEAD:${{ github.head_ref }}
          else
            echo "No changes to commit"
          fi