name: Lint

on:
  push:
  pull_request:

jobs:
  lint:
    name: Lint with ruff and flake8
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.11"]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Ruff and Flake8
        run: |
          python -m pip install --upgrade pip
          pip install ruff flake8

      - name: Run Ruff
        run: |
          # Lint everything except tests; adjust path if needed
          ruff check custom_components

      - name: Run Flake8
        run: |
          flake8 custom_components --count --show-source --statistics
